services:
  front:
    build: ./front
    ports:
      - "80:80"         # Port local : port nginx
    depends_on:
      - middleware

  service1:
    build: ./service1
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=
  
  service2:
    build: ./service2
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=

  middleware:
    build: ./middleware
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=
    depends_on:
      - service1
      - service2
