version: '3.8'
services:
  front:
    build: ./front
    ports:
      - "3000:80"         # Port local : port nginx
    depends_on:
      - service1
      - service2

  service1:
    build: ./service1
    ports:
      - "8081:8080"
    environment:
      - JAVA_OPTS=
  
  service2:
    build: ./service2
    ports:
      - "8082:8080"
    environment:
      - JAVA_OPTS=
